<template>
  <content-container
    anchor="diari-simonebevilacquaretream"
    author="Antonio Bianchetti"
    date="30 Settembre 2018"
    title="Intervista a Simone Bevilacqua, la mente creativa di Retream"
    @announceBookmark="announceBookmark($event)"
    @dismissBookmark="dismissBookmark($event)">
    <content-section>
      <p>Siamo colelgati con <a href="https://twitter.com/R37R34M">Simone Bevilacqua</a> via Skype, la mente creativa dietro la software house <a href="https://www.retream.com">Retream</a>. È il 16 Luglio del 2018 e Simone sta lavorando a <a href="https://retream.itch.io/skillgrid">SkillGrid</a>, sullo stesso Amiga di quando era adolescente, mentre il suo gioco precedente, <a href="https://retream.itch.io/mah">MAH</a>, per C64, è giá in distribuzione.<br>
      Infatti varie e fortuite circostanze della vita hanno portato entrambi a collegarci dalle nostre camerette in cui abbiamo speso i migliori anni dell’adolescenza.<br>
      Simone è un game designer perfezionista, eclettico e creativo. I suoi giochi miscelano generi diversi in un mix innovativo e imprevedibile, lasciando anche spazio a tanto umorismo.
      Ma diamo la parola a Simone stesso, che, come capirete leggendo, è anche un gran chiacchierone.</p>

      <p><b>Zzap.it</b> Chi era Simone Bevilacqua all’epoca degli 8 e 16 bit? Un videogiocatore come tanti o già il programmatore creativo che conosciamo adesso?</p>

      <p><b>Simone Bevilacqua</b>: Ho giocato soprattutto sul C64, ma la maggior parte del tempo l’ho passata a programmare. Il primo Commodore l’ho avuto a 9 anni, il Bread Bin, e l’ho usato subito per scrivere le prime linee di codice. Ma sai, io ero isolato, vivendo a Campobasso non avevo contatti, avevo solo il manuale del BASIC che veniva con la macchina. Giocavo molto ma dagli 11 anni ho deciso di mettermi a programmare più seriamente, facendo gli esercizi per la scuola e disegnando in modo bitmap. Ricordo che scrissi un programma di paint con il <a href="https://archive.org/details/SimonsBASIC/page/n0">Simons’ BASIC</a>. Recentemente ho ritrovato tutte le vecchie cassette, le ho campionate dallo stereo recuperando tutti i miei primi esperimenti.<br>
      Poi sono passato all’Amiga e mi si è aperto un nuovo mondo. Ma ero sempre isolato e ho dovuto far tutto da me, così con <a href="https://it.wikipedia.org/wiki/AMOS_BASIC">l’AMOS</a> ho cominciato a fare qualcosa di più consistente e anche qualche giochino. Poi andando al laboratorio dell’Università ho scaricato finalmente i manuali dell’hardware e ho cominciato a “far palestra” programmando l’Amiga, l’ho usata ininterrottamente fino al 2003. Poi sono emigrato in Finlandia ma non l’ho portata con me, ho invece usato un <a href="https://it.wikipedia.org/wiki/AmigaOne">Amiga One</a>, che architetturalmente è un PC. Ma non trovavo nessun interesse nel programmare una scheda VGA, infatti lo sfizio nel programmare i vecchi computer è proprio quello di accedere all’hardware direttamente, fargli fare cose che non erano state pensate neanche dai progettisti. Però quella era l’evoluzione naturale dell’Amiga e speravo di usarlo tanto per programmare i miei giochi che per lavorare. Ed è li che provando a lavorare al livello più basso possibile, in C, ho creato il mi piccolo framework che mi permetteva di accedere all’hardware, il più possibile.<br>
      Ma la mia passione era un’altra e così nel 2007 sono ritornato al C64 in emulazione, fino poi a sviluppare i vari giochi che ho pubblicato. E poi l’anno scorso sono tornato anche all’Amiga perché non posso trascurarla per così tanto tempo, è una vergogna. Adesso ce l’ho montata qui a fianco e mi sto divertendo tanto a sperimentare e inventare nuove cose.<br>
      Tra parentesi, il Bread Bin mi morí, un giorno non si accese più. Qui al centro Commodore non mi diedero speranza quindi mio padre mi comprò il C64C, non sapendo che all’epoca erano già in giro gli Amiga. L’A1200 è arrivato nel ’93, ce n’è voluto di tempo!</p>


      <p><b>Z</b>: Possiamo dire che lo stare in una posizione di isolamento sia stato per te anche un vantaggio? Mi spiego meglio, l’avere solo il manuale base e non disporre di software in abbondanza spinge a passare dall’essere solo un consumatore al dover inventare tutto da se.</p>

      <p><b>SB</b>: Si è vero, io non sapevo neanche cosa fosse la demoscene. Vedere i risultati ottenuti da chi sfrutta l’hardware così bene come nelle produzioni della demoscene rallegra.</p>

      <p><b>Z</b>: Parlando di giochi, quale stile di gioco era il tuo preferito?</p>

      <p><b>SB</b>: Per me i giochi erano le cassette in edicole, quelle da 10 giochi in uno. Poi un giorno scoprì che c’erano i giochi originali inscatolati, ero a casa di un amico che aveva il catalogo Soft Mail, e i miei occhi non ci credevano. Allora lo sfogliai e mi permisi di ordinare qualcosa, quando arrivò questa scatola enorme di Spiderman con dentro il fumetto. Una roba eccezionale! E ancora non facevo la connessione tra i giochi originali e quelli in edicola; per me il gioco che chiamava “Il Drago”, che era in realtà “Draconus” o “Savage”, adesso non ricordo, era quello della cassetta. Non sapevo niente della demoscene, dei crack, delle intro, dei giochi originali.</p>

      <p><b>Z</b>: Com’è nata Retream?</p>

      <p><b>SB</b>: Il primo gioco pubblicato è <a href="https://retream.itch.io/boh">BOH</a>, nel 2009, ce l’ho qui (mostra la scatola su Skype, NDR). Perché l’ho creato? Rientrato in Italia nel 2005, nel 2006 ho lavorato alla sovrintendenza ai beni culturali a un progetto per un anno. L’anno successivo come programmatore per un’azienda di Benevento, facendo il pendolare, 130 km in macchina. Ma io non posso fare il programmatore di professione. In Finlandia sì che programmavo ma facevo i driver grafici di uno smartphone, quindi qualcosa più vicino a quello che erano le mie propensioni. Il lavoro a Benevento finí, l’anno dopo vinsi una borsa di studio con l’Università per un progetto sullo sviluppo del turismo, ma poi finito il progetto finito tutto. L’Italia era già così, il posto fisso non esisteva più. In tutto questo tempo sviluppavo giochi tra cui il motore grafico sul quale era basato BOH che aveva un gran potenziale, creava un’atmosfera che ti immergeva in un mondo claustrofobico e misterioso. Ci feci una intero gioco attorno e decisi di commercializzarlo e pubblicato professionalmente per Amiga. Parliamo di Amiga di nuova generazione, <a href="https://en.wikipedia.org/wiki/AmigaOS_4">Amiga OS4</a>. Contavo su una sorta di scambio, da parte mia davo il primo gioco commerciale di qualità per il sistema, e in cambio contavo sul supporto della scena Amiga. Il gioco girava anche su Windows ma se fai un gioco solo per Windows al giorno d’oggi, dove vai? Così è stato uno dei primi giochi originali pubblicati per Amiga OS e il primo pubblicato fisicamente.<br>
      Avevo già pubblicato dei giochi freeware per Amiga classico, quelli che avevo sviluppato da giovanissimo, ma questa è stata la prima volta che ho provato la strada commerciale. Ancora non esisteva l’etichetta Retream, ma era pubblicato da Editel, un editore locale attivo nel campo del Marketing che mi ha supportato.<br>
      L’etichetta Retream nasce invece per caso, il mio sito personale era su Interfree, quando il servizio passa a pagamento decisi di comprare il mio dominio e pensai al nome Retream, che viene dall’unione di “retro” e “dream”. Le produzioni vecchio stile mi hanno fatto sempre sognare, stimolano di più la fantasia, mi proiettano in un mondo dove il mio cervello è impegnato a creare  un concetto da pochi pixel. Le produzioni moderne non mi interessa proprio, zero zero, nonostante ne apprezzi le qualità  tecniche e ingegneristiche. Già vivo in una realtà con infiniti milioni di poligoni al secondo, preferisco sognare con i tre pixel messi uno vicino all’altro che rappresentano un qualcosa.<br>
      Da allora uso il nome per tutti i giochi che ho rilasciato nel tempo.<br>
      E così ho risposto alla tua domanda :)</p>

      <p><b>Z</b>: Una risposta dettagliatissima Simone! Retream ci sembra un nome veramente azzeccato, ci è piaciuto sin dalla prima volta che l’abbiamo visto.</p>

      <p><b>SB</b>: Grazie, mi fa piacere che ti piaccia! Mica ci ho pensato tanto, mi sembra che guidavo quando ho focalizzato questa idea. Si basa sul mondo onirico del bambino. Lavoro sui computer perché all’età di 7 anni vidi il C64 di mio cugino e mi si aprí un mondo, a parte la bellezza di quello che vedevo mi colpí ciò che si poteva esprimere. Poteva potenziare la fantasia in un modo incredibile.<br>
      Per me prima la creatività era quella dei LEGO, ho iniziato da bambino e se avessi il tempo continuerei ancora oggi, ma questo è un livello superiore, creando tutto insieme, la musica, la grafica, è qualcosa di fantastico. Per me è un sogno.<br>
      Tornando alla tua domanda, questa è stata la componente che mi ha spinto a scegliere il nome Retream.</p>

      <p><b>Z</b>: Parlando delle possibilità creative offerte dai computer, ricordiamo molto bene un concetto trovato nella biografia di Steve Jobs di Walter Isaacson. Inizialmente la comunità controculturale degli anni 60 vedeva i computer negativamente, in quanto strumenti del potere e addirittura orientati all’uso prevalentemente militare. Solo tempo dopo cominciarono a vederne il potenziale creativo in grado di aprire le famose “porte della percezione”, espandendo la mente umana e le sue capacità immaginifiche.</p>

      <p><b>SB</b>: Si, la gente fa fatica a capire come un informatico, io ho preso pure la laurea, non trovi lavoro. Mi dicono ma come, tu hai la passione, hai il titolo, potresti trovare lavoro come programmatore. Ma io non ci riesco perché per me sviluppare è una questione di cuore, il computer è per me come la tela e il pennello per il pittore, è il mezzo che mi permette di esprimere il sogno che ho dentro. Un potenziale che è superiore a quello della tela, senza sminuire la bellezza dell’arte pittorica. Ma il computer non esprime solo la parte visiva, permette di unite anche la narrativa e la logica, e apre possibilità infinite.</p>

      <p><b>Z</b>: Parlando di lavoro, una notizia apparsa su Twitter che ha fatto molto parlare è stata la dichiarazione di <a href="https://twitter.com/JasonNapalm">Jason Aldred</a>, il programmatore di Galencia, che incredulo dichiarava il suo stupore nell’aver firmato un contratto che gli sta permettendo, nel 2018, di potersi mantenere, almeno per un po’ di tempo, programmando un gioco per Commodore 64 (Galencia Chaos Sphere). Ovvero vivere lavorando a ciò che più lo appassiona.<br>
      Come prendi questa notizia, credi sia un caso eccezionale o questa seconda giovinezza del C64 può dare lavoro, remunerato dignitosamente, ad altri game designer altrettanto bravi e motivati?
        <Tweet
          :id="'1013827286674608128'"
          :widget-class="'content__tweet'">
          <div class="content__loader"/>
        </Tweet>
      </p>

      <p><b>SB</b>: È incredibile sì, ma non è ancora possibile viverci. So che lui ha fatto dei bei numeri. Io sono in contatto con <a href="https://www.protovision.games/">Protovision</a> perché mi hanno pubblicato la versione su disco di MAH, e quindi ho accesso a informazioni interne. Posso dire che Sam Journey, che ha avuto un successo enorme, siamo a livelli notevoli superiori a Galencia, nonostante questo i ricavi non possono assolutamente permettere agli sviluppatori di dire “facciamo un altro gioco e viviamo di questo”. Sono sì grandi soddisfazioni ed avere quel tipo di introito è molto positivo ma siamo ancora lontani.<br>
      Penso anche a progetti come <a href="https://www.kickstarter.com/projects/stirringdragongames/unknown-realm-an-8bit-rpg-for-pc-and-commodore-64">Unknown Realm</a>, che su Kickstarter ha raccolto 126.000 dollari, per un gioco del C64 che offre pure una versione per PC, simulando l’ambiente hardware dell’8 bit. È una cifra spropositata ma credo ci lavorino da 4-5 anni, non so a che ritmi. Poi la velocità è relativa, io sono uno che ci mette anni a cesellare l’ultimo pixel, magari un gioco che un’altra persona ci metterebbe 7 mesi io ci impiego 3 anni perché sono maniaco, ho i miei ritmi. Comunque quelli di Unknown Realm sono un piccolo team, mentre io sono da solo. Certo loro hanno associato al gioco molti gadget, poi devi togliere le spese, dividerli tra il team, dividerli per il numero di anni. Il guadagno effettivo, che pure c’è non è così grande come la cifra lascia suggerire. Comunque è un progetto che ha trovato più di mille e duecento “backers”, magari gente scocciata di tutti questi giochi ultra moderni che apprezza il vecchio modo di vedere le cose, oltre al fattore nostalgia, che fa presa sulla nostra generazione.<br>
      Magari potessi campare dei miei giochi!</p>

      <p><b>Z</b>: Rimanendo sui progetti moderni finanziati tramite Kickstarter, recentemente abbiamo contribuito come beta tester al progetto <a href="https://www.kickstarter.com/projects/thalamusdigital/hunters-moon-remastered">Hunter’s Moon Remastered</a> di <a href="http://www.thalamusdigital.co.uk/">Thalamus Digital</a>. Il progetto è stato finanziato con successo superando di poco la soglia minima e sbloccando alcuni degli “stretch goal". Abbiamo constato direttamente come tutto il team sta lavorando con passione e professionalità e si sarebbe meritato ancora più appoggio dalla comunità retrogamer.</p>

      <p><b>SB</b>: Chi lavora a questi progetti lo fa per passione. Recentemente è stata pubblicata la schermata di caricamento di Hunter’s Moon Remastered e lì si vede che ci sta dietro passione, tecnica e l’esperienza di anni di lavoro nel settore. Infatti i prodotti che vengono fatti oggi sono di qualità notevole, grazie alle capacità acquisite e agli strumenti per gli sviluppatori disponibili adesso che prima non esistevano.</p>

      <p><b>Z</b>: Parlando di programmazione, il tuo lavoro è decisamente multipiattaforma, come si può notare dando un rapido sguardo alla pagina di Retream. Quante piattaforme supporti e come?</p>

      <p><b>SB</b>: BOH, la nuova versione, riassume nove anni di miglioramenti gratuiti. Dopo 11 anni di sviluppo le due versioni, vecchia e nuova, sono state pubblicate insieme in un’edizione di lusso. Boh è scritto in C e compilato per girare nativamente su Amiga OS 4, dove è stato sviluppato, su <a href="http://aros.sourceforge.net/">AROS</a>, l’altro sistema operativo per Amiga, sui PC moderni da Windows XP in su, e su Linux e Mac, quest’ultimo sia PowerPC che X86. Tutto nativamente grazie el mio ambiente di sviluppo custom.<br>
      Per PC ho rilasciato anche <a href="https://retream.itch.io/huenison">Huenison</a>.</p>

      <p><b>Z</b>: Riguardo la scelta della piattaforma, come nasce un gioco di Retream? Idei prima il gioco e poi scegli la piatta ideale per svilupparlo o sono le capacità peculiari di una piattaforma in particolare che ti ispirano il gioco?</p>

      <p><b>SB</b>: Diciamo che non scelgo in realtà. Quando sono passato a Amiga OS 4, volevo usare questa piattaforma per tutto, sia come computer di lavoro in generale, testi, email, musica e chiaramente anche per sviluppare in C. Nel 2004 ho iniziato a creare questo mio framework di lavoro astratto e ho fatto BOH. Huenison l'ho iniziato invece il 31 Dicembre 2010. Ho lavorato anche a progetti che non hanno visto la luce come uno shoot’em up  gestionale, troppo complesso per lavorarci da solo. Inoltre troppe idee messe insieme sarebbero state apprezzate solo da pochi, era troppo macchinoso, e lo chiusi. Ma lavorare in C non è soddisfacente tanto come programmare direttamente l’hardware del C64 e dell’Amiga.<br>
      Così sono tornato sul C64, parlando con alcuni publishers, volevo riscoprire questa macchina che da ragazzino non avevo avuto la possibilità di approfondire per mancanza di documentazione. Ho cominciato con programmini in BASIC, senza pretese, giusto per divertirmi. Poco dopo mi è tornata la fisa che avevo da ragazzino per gli sprite multicolore in alta risoluzione. Da bambino avevo fatto un editor ma era inutilizzabile. Dopo questi esperimenti decisi di spingermi oltre facendo un gioco intero in alta risoluzione, in BASIC!<br>
      Ho iniziato giusto per provare a sperimentare, anche con l’extended color mode. È venuto fuori <a href="https://retream.itch.io/quod-init-exit">Quod Init Exit</a>, il gioco del maialino. Ho iniziato a proporlo alla scena C64.<br>
      La storia parte da una frase di un amico e da li arrivai al maialino che mangia tutto, con gli sprite multicolori ma ne volevo parecchi su schermo e quindi usai il multiplexing, da questo la creazione delle piattaforme con livelli sfalsati. Tutto grazie all’idea di un amico a cui piace mangiare.<br>
      <a href="https://www.rgcd.co.uk/">RGCD</a> mi publicò la cartuccia, me lo chiesero loro. Io lo vedevo come una cosina semplice ma alla gente è piaciuto molto, persino mi mandano foto dei loro bambini anche di 5 anni che giocano a Quod Init Exit. Una gioia fantastica.<br>
      Quindi sono tornato al C64 e all’Amiga per puro piacere, non perché avevo in mente un progetto commerciale. Così come sono tornato su Amiga, perché avevo una voglia repressa da anni. Purtroppo il tempo è limitato ma avevo voglia di programmare un motore di scrolling a layer con parallasse e trasparenze con musica a 14 bit. Ho pensato, ora ci faccio un gioco e ho cominciato a sviluppare SkillGrid.<br>
      Io parto dal mio divertimento personale e dagli aspetti tecnici, non dalla parte commerciale.<br>
      Il seguito di Quod Init Exit, che è un platform multi direzionale, nasce da un risultato tecnico di MAH. Nel finale di MAH avevo implementato uno scrolling multi direzionale bellissimo ma che solo poche persone avrebbero visto, non perché sono cattivo ma perché è un gioco che richiede impegno e oggi la gente non ha ne il tempo ne la voglia di impegnarsi più di tanto. Pensa che nelle prime versioni pubbliche di MAH, c’è proprio un messaggio scritto piccolissimo: “a new game with this?”. E alla fine ci ho costruito Quod Init Exit. Quindi sono partito da un obiettivo tecnico, un voler andare al di la delle barriere e direi che quasi tutti i miei giochi cominciano così, voglio innanzi tutto divertirmi io. Non scelgo la piattaforma.<br>
      Adesso in cuor mio ho deciso che non voglio andare più sul PC, ho altri progetti in cantiere e per qualche anno, o forse per sempre, voglio fare solo giochi per C64 e Amiga.<br>
      Per il prossimo Quod Init Exit 2, anzi “secundus” ci vorrà un annetto e mezzo di lavoro, c’è tanta grafica da disegnare e musica e disegni da fare. La prima versione è solo un giochino e mentre lo stavo creando ho deciso che volevo partecipare alla competizione di giochi da 16k organizzata da RGCD. Purtroppo mancai la deadline per una stupidaggine. Il giorno della deadline fornii a James l’eseguibile in formato RPG ma doveva essere per cartuccia. Non l’avevo mai fatto. Ci provai ma non feci in tempo a causa di un problema di bank switching che risolsi solo i giorno dopo. Ma l’idea era quella di fare un platform completo con presentazione, multilivello, ma ci sono tanti contenuti da fare e poco tempo di CPU per migliorare il gameplay ma alcuni elementi riuscirò ad aggiungerli.<br>
      Su amiga sto lavorando a SkillGrid, userà musica campionata suonata da me stesso e la sto registrando in questi giorni. Di base c’è il motore di scrolling di cui parlavo e in più ci sarà musica di alta qualità lossless, il tutto dovrà girare sull’Amiga 1200 di base, quindi con due mega. Mi sono inventato un algoritmo di compressione veloce che il 68020 può decomprimere al volo (compila il gioco durante l’intervista per mostrarcelo, NDR). Funzionerà anche da floppy, con questo loop di 5 secondi. È un misto tra uno shoot’em up e un puzzle game. Nel gioco per adesso c’è la sigla di Jeeg Robot, una delle ultime cose da fare è registrare la musica.</p>

      <p><b>Z</b>: Quindi crei le musiche tu stesso. Ma fai proprio tutto tu quindi, non hai collaboratori?</p>

      <p><b>SB</b>: Esatto, è una conseguenza di quello che dicevamo. Lo stare isolato mi ha obbligato ad arrangiarmi e quindi anche a fare la grafica e la musica. Qualche volta ho provato a collaborare con qualcuno ma sono super esigente, non sono una persona con cui è facile lavorare.<br>
      Adesso in SkillGrid sono al punto in cui non ho più memoria per far nulla, è un gioco che ha poche pretese riguardo al gameplay, è più un esperimento tecnico. È un gioco che faccio per divertimento, un giochino, non sarà un gioco lungo. Sto migliorando l’algoritmo di compressione, se riesco a ricavare 100 o 200k aggiungerò qualche boss. La musica adesso occupa circa un mega e sei. Ma il mio obiettivo è fare una cosa diversa, non mi importa se non verrà etichettato come il degno successore di Banshee, è un gioco diverso con un altro obiettivo. Spero di rilasciarlo a breve.<br>
      Ho anche altri engine grafici che vorrei usare, uno è in attesa di essere usato dagli anni 90. Se riesco a sfruttare tutto quello che ho già pronto potrei fare altre quattro release, ma ci vogliono tanti anni. Inoltre mi è sempre piaciuto focalizzarmi su uno progetto alla volta, e quindi vorrei prima chiudere con SkillGrid.<br>
      C’è tanto da fare ma al momento non ho un lavoro fisso e quindi ho molto tempo da dedicare ai giochi.</p>

      <p><b>Z</b>: I tuoi giochi sono disponibili in vari formati e tramite vari canali come negozi online e anche venduti direttamente da te. Qual’è la situazione attuale della distribuzione delle copie fisiche?</p>

      <p><b>SB</b>: Riguardo la distribuzione dei giochi, recentemente ho contattato <a href="https://twitter.com/robhewson">Rob Hewson</a>, per chiedergli se fosse interessato a pubblicare BOH. Perché spedire qui dall’Italia con i prezzi che ci sono, pure aumentati di recente, ti stronca. Pensa che chi dalla Spagna si è comprato BOH e Huenison ha pagato €18 di spedizione e adesso vale quasi 20. Come posso io chiede €40/€50 per il gioco quando poi devi aggiungere queste cifre per la spedizione? Devo mantenere i costi bassi. Quando Protovision mi ha spedito dalla Germania la copia di MAH, che è un bel mattone, ho pagato solo €6,50, non 20.<br>
      La versione su cartuccia di MAH viene distribuita con un manuale completo di sedici pagine, mentre la versione disco, essendo più economica ma avendo una scatola più grande, ha al posto del costoso manuale delle schede riassuntive del gioco. Sono sette screenshoot rielaborati, doppia faccia, utilissimi per consultare rapidamente le dinamiche di gioco.<br>
      In ogni caso la documentazione è importantissima per capire pienamente le meccaniche di gioco di MAH, perché è fatto di tanti elementi semplici che però tutti insieme richiedono di fare attenzione a quello che si vede sullo schermo, e il manuale aiuta molto.<br>
      La cartuccia è quasi in esaurimento, di dischi ne rimangono tanti (Luglio 2018, NDR). La tiratura originale dell’edizione disco è di cento copie, tantissime per un prodotto di questo tipo.<br>
      C’è anche la versione digitale ma io venderei solo copie fisiche, nonostante quelle digitali siano più convenienti visto che non ci sono spese per ogni copia addizionale venduta.<br>
      Dimenticavo! Alla fine Rob mi ha chiesto se andassi a una fiera per sviluppatori all’estero ma io per il momento sto qua, magari!</p>

      <p><b>Z</b>: Una parte fondamentale delle versioni fisiche dei giochi è la confezione e la copertina. Non farai anche tu pure l’artwork?</p>

      <p><b>SB</b>: Certo! Anche l’artwork delle versioni fisiche l’ho fatto io, io faccio tutto!  Ho un livello maniacale per i dettagli, tutto allineato al pixel, alla perfezione, e stampato a 600 DPI :-)<br>
      Ma non si noterà mai? Non importa, voglio che sia perfetto.<br>
      Ti svelo una cosa (prende una scatola della versione disco di MAH, NDR), c’è scritto "creato nel 2015 e migliorato nel 2017 da Simone Bevilacqua,  pubblicato nel 2017 da Protovision. E no! È sbagliato. Per aspettare RGCD venne pubblicato nel 2018. Gli mandai la grafica aggiornata ma pubblicarono la vecchia versione, con la data sbagliata. Non sai quanto mi ferisce! Disturba la perfezione a cui miravo (per fortuna la versione su cartuccia pubblicata da RGCD che abbiamo in redazione riporta le date correttamente).<br>
      In Huenison invece ho fatto io stesso un errore di questo tipo. Tutta la grafica del gioco è in dot matrix, e anche l’artwork è tutto in dot matrix. Avevo questa fissa da ragazzino, quando la vedevo in Pinball Fantasy. Il carattere che ho usato nell’artwork è lo stesso usato nel gioco e ha una particolarità: l’allineamento tra maiuscole e minuscole è centrato invece che essere allineato sulla linea base delle lettere. Ebbene, nella copertina ho sbagliato l’allineamento di due lettere, una “I” e una “H”. Me ne sono accorto solo dopo aver ricevuto una copia della scatola.<br>
      Io investo mesi nel realizzare l’artwork e i manuali. I manuali li leggo e rileggo fino al punto da non vederne più gli errori. Sono ultra dettagliati, 20 pagine Huenison e 24 BOH.<br>
      Quando ne parlo ai miei amici mi ridono quasi in faccia, nessuno noterà mai queste imperfezioni. Io creo i giochi in questo modo, faccio persino attenzione ai commenti del codice, correggendo la grammatica e rendendo lo stile uniforme. Poi pago lo scotto quando mi rendo conto che la perfezione a cui tendo è fuori dalla mia portata, essendo un essere umano. Devo accettarlo.</p>

      <p><b>Z</b>: MAH ci ha colpito molto, soprattutto la grafica e il gameplay. Hai inoltre creato una storia epica e cupa attorno al pericolo di una fine incombente per tutta l’umanità, una storia Apocalittica. Continuando a leggere la descrizione però la storia si collega sorprendentemente a quella di un maialino goloso. Puoi dirci di più sull’ironia che collega i titoli di Retream? :-)</p>

      <p><b>SB</b>: È un’idea che ho avuto a posteriori, quella di unire tutti i miei giochi in una saga. La storia parte proprio da BOH, in cui ho inventato questi Evil Master che arrivano seminando distruzione.<br>
      Poi a posteriori ho collegato Huenison. Ho pensato, facciamo che i Mind Control Wells sono stati creati da un Evil Master per farti impazzire. Tu come giocatore lo sfidi a questi puzzle molto mentali e frenetici. Poi ho pensato, ok continuiamo questa storia. Diciamo che Huenison è stato sconfitto e gli Evil Master se ne sono andati dalla terra. Strada facendo sono capitati sul pianeta Suinio, e qui viene la svolta umoristica. Anche Huenison è spiritoso pur nella sua cattiveria. All’interno della confezione c’è il CD, che funziona anche da CD audio, e sul CD c’è una domanda del Evil Master che ti chiede: “quanto sono bravo a farti ascoltare questa musica meravigliosa mentre ti faccio impazzire?”. Durante il gioco ti bombarda di messaggi cattivi però sono in tono spiritoso.<br>
      Come dicevamo, in Quod Init Exit l’elemento umoristico è più esplicito. I cattivoni arrivano su questo pianeta così felice  dove il cibo gira tutto intorno gratuitamente e una strega locale per scacciarli lancia un incantesimo che li fa fuggire in preda a coliche pazzesche. Purtroppo l’incantesimo è cosí potente che distrugge i gabinetti o li fa diventare piccoli, delle mini tazzine sparse per il mondo. Zampo, il protagonista, deve raccoglierle.<br>
      Dopo, in MAH siamo di nuovo sulla terra, è passato molto tempo, solo rimane la memoria degli Evil Master. Loro se ne sono andati ma gli esseri umani hanno continuato a farsi la guerra, a devastarsi tra di loro, e qui c’è una critica al mondo. E dei matti pensano si può purificare la terra solo sterminando l’intera razza umana. Come dicevi MAH è una storia molto seria. E quindi il tuo compito è crackare la bomba che era stata prodotta per distruggere tutto, anche gli Evil Master. Un sacrificio pensato per fermarli ed evitare che portino il loro male in altri luoghi dell’universo.<br>
      L’ultima tappa della storia è <a href="https://retream.itch.io/kog">KOG</a>, disponibile solo in digitale. Come svelato nel finale di MAH, l’idea è che il salvatore, colui che in MAH ha salvato il mondo, torna alla sua colonia, un luogo di pace che non conosce la guerra, e durante il viaggio ragionando si chiede cosa troverà al suo arrivo, se ci sarà la guerra ad aspettarlo. E infatti il suo mondo sembra prepararsi a una guerra e gli viene chiesto di costruire un software per allenare eventuali corpi di sicurezza. Il gioco consiste proprio in questo training. KOG è un gioco arcade con elementi puzzle e sto pensando di inserire SkillGrid in questo steso filone, come un’altra fase del training in cui si addestra la popolazione a proteggersi per garantire la pace.<br>
      La storia ha una visione molto negativa del mondo e non credo si riesca a raggiungere la pace veramente. Ma alla fine il tutto è un divertimento e ogni gioco è godibile separatamente.</p>

      <p><b>Z</b>: E adesso parliamo brevemente di Zzap! Eri un lettore della nostra rivista preferita? Qualche aneddoto da raccontare?</p>

      <p><b>SB</b>: Non l’ho mai visto in edicola o forse non l’ho mai notato. Non avevo disponibilità economica a quell’epoca ma non c’era proprio il concetto di comprare una rivista di videogiochi. Un amico comprava TGM ma prima ancora un’altro comprava C+VG, quando era in formato piccolo, non ancora A4. Lí vidi per la prima volta qualcosa che assomigliasse a una recensione.<br>
      Solo verso il quarto superiore comprai alcuni numeri di TGM dopo aver inviato alla redazione dei giochi fatti con l’Amos, per la rubrica Talent Scout. Speravo qualche giorno di vedere il mio gioco pubblicato sul giornale ma non avvenne mai. A posteriori forse avevano ragione :-).<br>
      Sí che a Pisa comprai Amiga Format, avevano i magazine inglesi con i cover disk. Non ci credevo! E li conservo ancora, non le riviste ma tutti i dischi allegati (ce li mostra su Skype, NDR). Poi quando studiai a Pisa sì che comprai qualche giornali, fino al fallimento della Commodore e dell’indotto editoriale.<br>
      Mai avuto una copia di Zzap! tra le mani. Forse non è mai arrivato a Campobasso.</p>

      <p><b>Z</b>: Ci dispiace che Zzap! non sia riuscito ad arrivare al cuore di Simone durante la sua infanzia, purtroppo tutti abbiamo conosciuto, in qualche momento, le idiosincrasie della distribuzione cartacea in edicola.<br>
      Ringraziamo Simone per essere stato così disponibile nel concede questa lunga intervista a Zzap!. Torniamo a dare energia alla nostra cartuccia di MAH mentre rimaniamo con gli occhi ben aperti per seguire gli sviluppi della tua ondata creativa.</p>

    <br>
    <br>
    <div>
      <h2>Trivia MAH</h2>
      <p>MAH, nasce dalla fissa per gli sprite in alta risoluzione colorati. Una fissa che avevo da bambino. Per avere sia alta risoluzione che tanti colori sul C64 bisogna sovrapporre gli sprite, è un punto debole della macchina. Ho detto, “facciamolo diventare un punto di forza, costruiamoci un intero gioco”. Infatti nella fase iniziale del gioco i 4 nemici a causa di un certo evento si uniscono per formare uno sprite multicolore. Volevo proprio far vedere alla gente questa unione, anche pensando a quei robot dei cartoni animati giapponesi che si uniscono.</p>

      <p>Il MAH in vendita adesso è la nuova versione, frutto di una riscrittura totale che ha raddoppiato i contenuti del gioco. 
      Protovision voleva che uscisse con un nuovo nome, MAH Ultimate o MAH 2, per non confonderlo con la versione precedente. Ma per me questa era la versione finale di MAH e quindi il nome non doveva cambiare.
      Della prima versione esiste un crack che purtroppo disabilita un elemento fondamentale della prima fase del gioco, l’arma principale, senza la quale non si può progredire nel gioco. Contattai l’hacker e glielo spiegai, non ci avevano capito niente di questo gioco! È come se in Ghost and Goblins togli la lancia o il coltello, che fa Arthur, combatte a sputi?</p>

      <p>MAH è pieno di segreti da scoprire e non ci sono cheat.</p>

      <p>Non vi sembra abbastanza? Nella versione su cartuccia di MAH trovate un <a href="https://twitter.com/R37R34M/status/1031951289855430657">easter egg</a> favoloso!</p>
    </div>
    </content-section>

  </content-container>
</template>

<script src="./simone-bevilacqua-retream.js"></script>